services:
  ros_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WEBOTS_VERSION: ${WEBOTS_VERSION:-R2025a}
        WEBOTS_DEB: ${WEBOTS_DEB:-webots_2025a_amd64.deb}
    image: ros2-jazzy-sim:latest
    container_name: ros2_jazzy_sim
    stdin_open: true
    tty: true
    restart: "no"
    shm_size: "2gb"
    ipc: host
    network_mode: host
    environment:
      DISPLAY: ${DISPLAY}
      QT_QPA_PLATFORM: xcb
      QT_X11_NO_MITSHM: "1"
      XDG_RUNTIME_DIR: /tmp/runtime-ros
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RCUTILS_COLORIZED_OUTPUT: "1"
      WEBOTS_HOME: /usr/local/webots
      ROS2_WEBOTS_HOME: /usr/local/webots
      LIBGL_ALWAYS_INDIRECT: "0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/ros2_ws/src:rw
      - ros2_build_cache:/ros2_ws/build
      - ros2_install_cache:/ros2_ws/install
      - ros2_log_cache:/ros2_ws/log
      - webots_cache:/home/ros/.cache/Cyberbotics
      - webots_config:/home/ros/.config/Cyberbotics
      - gz_cache:/home/ros/.gz
    entrypoint: ["/entrypoint.sh"]
    command: ["bash"]

volumes:
  ros2_build_cache:
  ros2_install_cache:
  ros2_log_cache:
  webots_cache:
  webots_config:
  gz_cache:
